var Page;

Page = (function() {
  function Page() {}

  Page.openTasksList = function() {
    browser.setLocation('/tasks');
    return new TasksListPage();
  };

  Page.openSingleTask = function(taskId, showDetails) {
    if (showDetails == null) {
      showDetails = false;
    }
    browser.setLocation("/tasks/" + taskId + "?showDetails=" + showDetails);
    return new SingleTaskPage();
  };

  Page.openReleasesList = function(filter) {
    var url;
    url = this.appendFilterQueryString('/releases', filter);
    browser.setLocation(url);
    return new ReleasesListPage();
  };

  Page.openTemplatesList = function() {
    browser.setLocation("/templates");
    return new TemplatesListPage();
  };

  Page.openRelease = function(releaseId) {
    browser.setLocation("/releases/" + releaseId);
  };

  Page.openTemplate = function(templateId) {
    browser.setLocation("/templates/" + templateId);
    return new ReleasePage;
  };

  Page.openReleaseOnGanttPage = function(releaseId) {
    browser.setLocation("/releases/" + releaseId);
    return new ReleaseGanttPage();
  };

  Page.openReleaseOnGridPage = function(releaseId) {
    browser.setLocation("/releases/" + releaseId);
    return new ReleaseGridPage();
  };

  Page.appendFilterQueryString = function(url, filter) {
    var key, queryString, value;
    if (filter) {
      queryString = ((function() {
        var results;
        results = [];
        for (key in filter) {
          value = filter[key];
          if (value) {
            if (value === true) {
              results.push("" + key);
            } else {
              results.push(key + "=" + (encodeURIComponent(value)));
            }
          }
        }
        return results;
      })()).join('&');
      if (queryString) {
        url += '?' + queryString;
      }
    }
    return url;
  };

  Page.openSmtp = function() {
    browser.setLocation('/smtp');
    return new SmtpPage();
  };

  Page.openServers = function() {
    browser.setLocation('/servers');
    return new ServersPage();
  };

  Page.openPermissions = function() {
    browser.setLocation('/permissions');
    return new PermissionsPage();
  };

  Page.openGeneralSettings = function() {
    browser.setLocation('/general-settings');
    return new GeneralSettingsPage();
  };

  Page.openGlobalVariables = function() {
    browser.setLocation('/global-variables');
    return new VariablesPage('#global-variables');
  };

  Page.openRoles = function() {
    browser.setLocation('/roles');
    return new RolesPage();
  };

  Page.openUsers = function() {
    browser.setLocation('/users');
    return new UsersPage();
  };

  Page.openTaskAccess = function() {
    browser.setLocation('/task-access');
    return new TaskAccessPage();
  };

  Page.openProfile = function() {
    browser.setLocation('/profile');
    return new ProfilePage();
  };

  Page.clearClientSettings = function() {
    return Browser.executeVoidScript(function() {
      var $injector, $rootScope;
      $injector = angular.element('body').injector();
      $rootScope = $injector.get('$rootScope');
      return $rootScope.$apply(function() {
        var ClientSettings;
        ClientSettings = $injector.get('ClientSettings');
        return ClientSettings.clear();
      });
    });
  };

  Page.openCalendar = function() {
    browser.setLocation('/calendar');
    return new CalendarPage();
  };

  Page.openPipeline = function() {
    browser.setLocation('/pipeline');
    return new PipelinePage();
  };

  Page.openConfiguration = function() {
    browser.setLocation('/configuration');
    return new ConfigurationPage();
  };

  Page.openReleaseValueStream = function(filter) {
    var url;
    url = '/release-value-stream';
    if (filter) {
      url += "?has_filter&filter=" + filter;
    }
    browser.setLocation(url);
    return new ReleaseValueStreamPage();
  };

  Page.openDashboardReports = function(filter) {
    var url;
    url = '/dashboard';
    if (filter) {
      url += "?has_filter&" + filter;
    }
    browser.setLocation(url);
    return new ReportDashboardPage();
  };

  Page.openReleaseAutomationReports = function() {
    return browser.setLocation('/release-automation');
  };

  return Page;

})();

global.Page = Page;

// ---
// generated by coffee-script 1.9.2